# Generated by Django 5.2.2 on 2025-06-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=120, unique=True)),
                ('senha', models.CharField(max_length=25)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
