# Generated by Django 5.2.1 on 2025-06-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('senha', models.CharField(max_length=45)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/')),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
    ]
