# Generated by Django 5.2.2 on 2025-06-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0002_bairro_ocorrencia_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, default='img/icon-user.png', null=True, upload_to='fotos_usuarios/'),
        ),
    ]
