# Generated by Django 5.2.2 on 2025-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHome', '0006_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_usuarios/'),
        ),
    ]
